/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pc.views;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.model.Filters;
import org.bson.Document;
import org.bson.types.ObjectId;


/**
 *
 * @author danie
 */
public class informacion extends javax.swing.JPanel {

     String IDtecnico_update;

    public informacion() {
        initComponents();
        IDtecnico_update = Registro.IDtecnico_update;
        InitStyles();

        // Llamar a un método para cargar y mostrar la imagen
        showImage();
    }

    private void InitStyles() {
        // Configura estilos de tu JPanel si es necesario
    }

    // Método para cargar y mostrar la imagen desde MongoDB
    private void showImage() {
        // Supongamos que tienes una instancia de MongoDB y una colección llamada 'images'

        // Obtén la imagen desde la base de datos
        byte[] imageData = getImageFromMongoDB();

        // Convierte los datos de la imagen a un BufferedImage
        try {
            ByteArrayInputStream bis = new ByteArrayInputStream(imageData);
            BufferedImage image = ImageIO.read(bis);

            // Crea un JLabel para mostrar la imagen
            JLabel imageLabel = new JLabel(new ImageIcon(image));
            
            // Agrega el JLabel al JPanel 'bg' (o al contenedor que desees)
            bg.add(imageLabel);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private byte[] getImageFromMongoDB() {
        try (MongoClient client = MongoClients.create("mongodb+srv://Edalmarc:udrNYnjBDhQvub8x@bic-edalmarc.svgqcpw.mongodb.net/Edalmarc?retryWrites=true&w=majority")) {
            MongoDatabase database = client.getDatabase("Edalmarc");
            MongoCollection<Document> collection = database.getCollection("images");

            ObjectId idMasonValue = new ObjectId(IDtecnico_update);
            Document imageDocument = collection.find(Filters.eq("id_mason", idMasonValue)).first();

            if (imageDocument != null) {
                Document imageObject = imageDocument.get("image", Document.class);
                if (imageObject != null) {
                    org.bson.types.Binary imageData = imageObject.get("data", org.bson.types.Binary.class);
                    if (imageData != null) {
                        return imageData.getData();
                    } else {
                        System.out.println("Los datos de la imagen son nulos.");
                    }
                } else {
                    System.out.println("El objeto 'image' no se encontró en el documento.");
                }
            } else {
                System.out.println("La imagen no se encontró en la base de datos.");
            }

            return null;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 430));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(0, 0));
        bg.setPreferredSize(new java.awt.Dimension(750, 430));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    // End of variables declaration//GEN-END:variables
}
